In [19]:
import tsl
import torch
import numpy as np
import pandas as pd
%load_ext autoreload
%autoreload 2

print(f"tsl version  : {tsl.__version__}")
print(f"torch version: {torch.__version__}")

pd.options.display.float_format = '{:.2f}'.format
np.set_printoptions(edgeitems=3, precision=3)
torch.set_printoptions(edgeitems=2, precision=3)

# Utility functions ################
def print_matrix(matrix):
    return pd.DataFrame(matrix)

def print_model_size(model):
    tot = sum([p.numel() for p in model.parameters() if p.requires_grad])
    out = f"Number of model ({model.__class__.__name__}) parameters:{tot:10d}"
    print("=" * len(out))
    print(out)

tsl version  : 0.9.5
torch version: 2.8.0+cu129


In [20]:
from tsl.datasets import MetrLA

dataset = MetrLA(root='/home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/Data')

print(dataset)

MetrLA(length=34272, n_nodes=207, n_channels=1)


/home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/.venv/lib/python3.10/site-packages/tsl/datasets/metr_la.py:98: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(df.index[0], df.index[-1], freq='5T')
/home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/.venv/lib/python3.10/site-packages/tsl/datasets/metr_la.py:109: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df = df.replace(to_replace=0., method='ffill')


In [21]:
print(f"Sampling period: {dataset.freq}")
print(f"Has missing values: {dataset.has_mask}")
print(f"Percentage of missing values: {(1 - dataset.mask.mean()) * 100:.2f}%")
print(f"Has exogenous variables: {dataset.has_covariates}")
print(f"Covariates: {', '.join(dataset.covariates.keys())}")

Sampling period: <5 * Minutes>
Has missing values: True
Percentage of missing values: 8.11%
Has exogenous variables: True
Covariates: dist


In [22]:
print_matrix(dataset.dist)

0        1        2       3       4       5       6        7    \
0       0.00      inf      inf     inf     inf     inf     inf      inf   
1        inf     0.00  2504.60 8563.80 8572.50 9561.00 9590.00  2506.30   
2        inf  1489.30     0.00 6971.30 6978.30 9148.20 9177.10  3995.70   
3        inf  6805.90  9293.60    0.00 1745.50 6068.80 5401.50  9312.30   
4        inf  6606.70  9111.30 1767.40    0.00 4464.00 3655.90  9113.10   
..       ...      ...      ...     ...     ...     ...     ...      ...   
202      inf      inf 10987.10     inf     inf     inf     inf 10133.60   
203      inf 10723.20  9461.80     inf     inf     inf     inf  8608.30   
204      inf      inf      inf     inf     inf     inf     inf      inf   
205  9599.80      inf      inf     inf     inf     inf     inf      inf   
206 10119.90  9374.80      inf 7922.00 6154.50     inf 9810.50      inf   

        8        9    ...     197     198      199  200     201     202  \
0       inf      inf  ...     inf     inf  3764.70  inf     inf 9204.30   
1       inf      inf  ...     inf     inf      inf  inf 4941.90 7559.20   
2       inf      inf  ...     inf 9467.80      inf  inf 6431.40 7821.80   
3       inf      inf  ...     inf 5906.50      inf  inf     inf     inf   
4       inf      inf  ...     inf 7207.10      inf  inf     inf     inf   
..      ...      ...  ...     ...     ...      ...  ...     ...     ...   
202     inf      inf  ...     inf     inf      inf  inf 9098.90    0.00   
203     inf      inf  ...     inf     inf      inf  inf 7283.50     inf   
204 9189.80  3171.10  ... 3672.40     inf      inf  inf     inf     inf   
205     inf 10167.50  ...     inf     inf 10500.80  inf     inf     inf   
206     inf      inf  ...     inf 2757.20      inf  inf     inf     inf   

        203  204     205      206  
0       inf  inf 8114.80 10009.70  
1   7877.20  inf     inf      inf  
2   9366.60  inf     inf  9837.00  
3       inf  inf     inf  7604.40  
4       inf  inf     inf  8905.00  
..      ...  ...     ...      ...  
202 4072.70  inf     inf      inf  
203    0.00  inf     inf      inf  
204     inf 0.00     inf      inf  
205     inf  inf    0.00      inf  
206     inf  inf 9018.70     0.00  

[207 rows x 207 columns]

In [23]:
print(f"Default similarity: {dataset.similarity_score}")
print(f"Available similarity options: {dataset.similarity_options}")
print("==========================================")

sim = dataset.get_similarity("distance")  # or dataset.compute_similarity()

print("Similarity matrix W:")
print_matrix(sim)

Default similarity: distance
Available similarity options: {'distance'}
Similarity matrix W:


0    1    2    3    4    5    6    7    8    9    ...  197  198  199  \
0   1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.12   
1   0.00 1.00 0.39 0.00 0.00 0.00 0.00 0.39 0.00 0.00  ... 0.00 0.00 0.00   
2   0.00 0.72 1.00 0.00 0.00 0.00 0.00 0.09 0.00 0.00  ... 0.00 0.00 0.00   
3   0.00 0.00 0.00 1.00 0.63 0.00 0.01 0.00 0.00 0.00  ... 0.00 0.01 0.00   
4   0.00 0.00 0.00 0.63 1.00 0.05 0.14 0.00 0.00 0.00  ... 0.00 0.00 0.00   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.22  ... 0.13 0.00 0.00   
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.32 0.00   

     200  201  202  203  204  205  206  
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
1   0.00 0.03 0.00 0.00 0.00 0.00 0.00  
2   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
3   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
4   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
..   ...  ...  ...  ...  ...  ...  ...  
202 0.00 0.00 1.00 0.08 0.00 0.00 0.00  
203 0.00 0.00 0.00 1.00 0.00 0.00 0.00  
204 0.00 0.00 0.00 0.00 1.00 0.00 0.00  
205 0.00 0.00 0.00 0.00 0.00 1.00 0.00  
206 0.00 0.00 0.00 0.00 0.00 0.00 1.00  

[207 rows x 207 columns]

In [24]:
connectivity = dataset.get_connectivity(threshold=0.1,
                                        include_self=False,
                                        normalize_axis=1,
                                        layout="edge_index")

In [25]:
edge_index, edge_weight = connectivity

print(f'edge_index {edge_index.shape}:\n', edge_index)
print(f'edge_weight {edge_weight.shape}:\n', edge_weight)

edge_index (2, 1515):
 [[  0   0   0 ... 206 206 206]
 [ 13  36  58 ... 157 162 198]]
edge_weight (1515,):
 [0.08  0.163 0.031 ... 0.045 0.031 0.115]


In [26]:
from tsl.ops.connectivity import edge_index_to_adj

adj = edge_index_to_adj(edge_index, edge_weight)
print(f'A {adj.shape}:')
print_matrix(adj)

A (207, 207):


0    1    2    3    4    5    6    7    8    9    ...  197  198  199  \
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.03   
1   0.00 0.00 0.14 0.00 0.00 0.00 0.00 0.14 0.00 0.00  ... 0.00 0.00 0.00   
2   0.00 0.19 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
3   0.00 0.00 0.00 0.00 0.12 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
4   0.00 0.00 0.00 0.11 0.00 0.00 0.02 0.00 0.00 0.00  ... 0.00 0.00 0.00   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.09  ... 0.05 0.00 0.00   
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.05 0.00   

     200  201  202  203  204  205  206  
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
1   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
2   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
3   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
4   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
..   ...  ...  ...  ...  ...  ...  ...  
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00  

[207 rows x 207 columns]

In [27]:
print(f'Sparse edge weights:\n', adj[edge_index[1], edge_index[0]])

Sparse edge weights:
 [0.08  0.163 0.031 ... 0.045 0.031 0.115]


In [28]:
from tsl.data import SpatioTemporalDataset

torch_dataset = SpatioTemporalDataset(target=dataset.dataframe(),
                                      connectivity=connectivity,
                                      mask=dataset.mask,
                                      horizon=12,
                                      window=12,
                                      stride=1)
print(torch_dataset)

SpatioTemporalDataset(n_samples=34249, n_nodes=207, n_channels=1)


In [29]:
sample = torch_dataset[0]
print(sample)

Data(
  input=(x=[t=12, n=207, f=1], edge_index=[2, e=1515], edge_weight=[e=1515]),
  target=(y=[t=12, n=207, f=1]),
  has_mask=True
)


In [30]:
from tsl.data.datamodule import (SpatioTemporalDataModule,
                                 TemporalSplitter)
from tsl.data.preprocessing import StandardScaler

# Normalize data using mean and std computed over time and node dimensions
scalers = {'target': StandardScaler(axis=(0, 1))}

# Split data sequentially:
#   |------------ dataset -----------|
#   |--- train ---|- val -|-- test --|
splitter = TemporalSplitter(val_len=0.1, test_len=0.2)

dm = SpatioTemporalDataModule(
    dataset=torch_dataset,
    scalers=scalers,
    splitter=splitter,
    batch_size=64,
)


In [31]:
dm.setup()
print(dm)


{Train dataloader: size=24648}
{Validation dataloader: size=2728}
{Test dataloader: size=6849}
{Predict dataloader: None}


In [32]:
import torch.nn as nn

from tsl.nn.blocks.encoders import RNN
from tsl.nn.layers import NodeEmbedding, DiffConv
from einops.layers.torch import Rearrange  # reshape data with Einstein notation


class TimeThenSpaceModel(nn.Module):
    def __init__(self, input_size: int, n_nodes: int, horizon: int,
                 hidden_size: int = 32,
                 rnn_layers: int = 1,
                 gnn_kernel: int = 2):
        super(TimeThenSpaceModel, self).__init__()

        self.encoder = nn.Linear(input_size, hidden_size)

        self.node_embeddings = NodeEmbedding(n_nodes, hidden_size)

        self.time_nn = RNN(input_size=hidden_size,
                           hidden_size=hidden_size,
                           n_layers=rnn_layers,
                           cell='gru',
                           return_only_last_state=True)
        
        self.space_nn = DiffConv(in_channels=hidden_size,
                                 out_channels=hidden_size,
                                 k=gnn_kernel)

        self.decoder = nn.Linear(hidden_size, input_size * horizon)
        self.rearrange = Rearrange('b n (t f) -> b t n f', t=horizon)

    def forward(self, x, edge_index, edge_weight):
        # x: [batch time nodes features]
        x_enc = self.encoder(x)  # linear encoder: x_enc = xΘ + b
        x_emb = x_enc + self.node_embeddings()  # add node-identifier embeddings
        h = self.time_nn(x_emb)  # temporal processing: x=[b t n f] -> h=[b n f]
        z = self.space_nn(h, edge_index, edge_weight)  # spatial processing
        x_out = self.decoder(z)  # linear decoder: z=[b n f] -> x_out=[b n t⋅f]
        x_horizon = self.rearrange(x_out)
        return x_horizon

In [33]:
hidden_size = 32   #@param
rnn_layers = 1     #@param
gnn_kernel = 2     #@param

input_size = torch_dataset.n_channels   # 1 channel
n_nodes = torch_dataset.n_nodes         # 207 nodes
horizon = torch_dataset.horizon         # 12 time steps

stgnn = TimeThenSpaceModel(input_size=input_size,
                           n_nodes=n_nodes,
                           horizon=horizon,
                           hidden_size=hidden_size,
                           rnn_layers=rnn_layers,
                           gnn_kernel=gnn_kernel)
print(stgnn)
print_model_size(stgnn)

TimeThenSpaceModel(
  (encoder): Linear(in_features=1, out_features=32, bias=True)
  (node_embeddings): NodeEmbedding(n_nodes=207, embedding_size=32)
  (time_nn): RNN(
    (rnn): GRU(32, 32)
  )
  (space_nn): DiffConv(32, 32)
  (decoder): Linear(in_features=32, out_features=12, bias=True)
  (rearrange): Rearrange('b n (t f) -> b t n f', t=12)
)
Number of model (TimeThenSpaceModel) parameters:     18572


In [34]:
from tsl.metrics.torch import MaskedMAE, MaskedMAPE
from tsl.engines import Predictor

loss_fn = MaskedMAE()

metrics = {'mae': MaskedMAE(),
           'mape': MaskedMAPE(),
           'mae_at_15': MaskedMAE(at=2),  # '2' indicates the third time step,
                                          # which correspond to 15 minutes ahead
           'mae_at_30': MaskedMAE(at=5),
           'mae_at_60': MaskedMAE(at=11)}

# setup predictor
predictor = Predictor(
    model=stgnn,                   # our initialized model
    optim_class=torch.optim.Adam,  # specify optimizer to be used...
    optim_kwargs={'lr': 0.001},    # ...and parameters for its initialization
    loss_fn=loss_fn,               # which loss function to be used
    metrics=metrics                # metrics to be logged during train/val/test
)

In [35]:
from pytorch_lightning.loggers import TensorBoardLogger

logger = TensorBoardLogger(save_dir="logs", name="tsl_intro", version=0)

In [39]:
%load_ext tensorboard
%tensorboard --logdir logs

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


Reusing TensorBoard on port 6006 (pid 63885), started 0:08:00 ago. (Use '!kill 63885' to kill it.)

In [38]:
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(
    dirpath='logs',
    save_top_k=1,
    monitor='val_mae',
    mode='min',
)

trainer = pl.Trainer(max_epochs=100,
                     logger=logger,
                     limit_train_batches=100,  # end an epoch after 100 updates
                     callbacks=[checkpoint_callback])

trainer.fit(predictor, datamodule=dm)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
/home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:881: Checkpoint directory /home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/Data/logs exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type               | Params | Mode  | FLOPs
---------------------------------------------------------------------
0 | loss_fn       | MaskedMAE          | 0      | train | 0    
1 | train_metrics | MetricCollection   | 0      | train | 0    
2 | val_metrics   | MetricCollection   | 0      | train | 0    
3 | test_metrics  | MetricCollection   | 0      | train | 0    
4 | model         | TimeThenSpaceModel | 18.6 K | train | 0    
---------------------------------------------------------------------
18.6 K    Trainable params
0         Non-trainable params
18.6 K    Total params
0.07

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

/home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
Only args ['x', 'edge_weight', 'edge_index'] are forwarded to the model (TimeThenSpaceModel).


/home/theniche/Research/Hilbert-Bundle-Convolutional-Networks/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.


Epoch 99: 100%|██████████| 100/100 [00:03<00:00, 27.65it/s, v_num=0, val_mae=2.970, val_mae_at_15=2.520, val_mae_at_30=2.970, val_mae_at_60=3.630, val_mape=0.0824, train_mae=3.420, train_mae_at_15=2.860, train_mae_at_30=3.430, train_mae_at_60=4.230, train_mape=0.0953]

`Trainer.fit` stopped: `max_epochs=100` reached.


Epoch 99: 100%|██████████| 100/100 [00:03<00:00, 27.60it/s, v_num=0, val_mae=2.970, val_mae_at_15=2.520, val_mae_at_30=2.970, val_mae_at_60=3.630, val_mape=0.0824, train_mae=3.420, train_mae_at_15=2.860, train_mae_at_30=3.430, train_mae_at_60=4.230, train_mape=0.0953]
